apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.service.containerPort }}
  selector:
    app: devportal
  type: {{ .Values.service.type }}      
